openpam: Restore local change lost in merge.
This was originally added by joerg@ in rev. 1.4 with the message:

> Cast enum explicitly to different type.

Losing this change broke the clang build:

> dependall ===> lib/libpam/libpam
> /home/source/ab/HEAD-llvm/src/external/bsd/openpam/dist/lib/libpam/openpam_configure.c:306:16: error: implicit conversion changes signedness: 'pam_control_t' to 'int' [-Werror,-Wsign-conversion]
>                 this->flag = ctlf;
>                            ~ ^~~~
> 1 error generated.